/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomTime {
    }
}
declare global {
    interface HTMLCustomTimeElement extends Components.CustomTime, HTMLStencilElement {
    }
    var HTMLCustomTimeElement: {
        prototype: HTMLCustomTimeElement;
        new (): HTMLCustomTimeElement;
    };
    interface HTMLElementTagNameMap {
        "custom-time": HTMLCustomTimeElement;
    }
}
declare namespace LocalJSX {
    interface CustomTime {
    }
    interface IntrinsicElements {
        "custom-time": CustomTime;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-time": LocalJSX.CustomTime & JSXBase.HTMLAttributes<HTMLCustomTimeElement>;
        }
    }
}
